# Generated by Django 4.1.4 on 2022-12-14 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorType',
            fields=[
                ('st_id', models.AutoField(primary_key=True, serialize=False)),
                ('st_name', models.CharField(max_length=50)),
                ('st_high_value', models.FloatField(blank=True, null=True)),
                ('st_low_value', models.FloatField(blank=True, null=True)),
                ('st_unit', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'Sensor_type',
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('s_date', models.DateField(blank=True, null=True)),
                ('s_name', models.CharField(max_length=100)),
                ('s_lat', models.FloatField()),
                ('s_long', models.FloatField()),
                ('sensor_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sensortype')),
            ],
            options={
                'db_table': 'Sensor',
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('m_id', models.AutoField(primary_key=True, serialize=False)),
                ('m_value', models.FloatField()),
                ('m_timestamp', models.DateTimeField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sensor')),
            ],
            options={
                'db_table': 'Measurement',
            },
        ),
    ]
