# Generated by Django 4.1.4 on 2022-12-18 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='sensor',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='sensor_type',
        ),
        migrations.AddField(
            model_name='measurement',
            name='s_id',
            field=models.ForeignKey(db_column='s_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='core.sensor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensor',
            name='st_id',
            field=models.ForeignKey(db_column='st_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='core.sensortype'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='measurement',
            table=None,
        ),
        migrations.AlterModelTable(
            name='sensor',
            table=None,
        ),
        migrations.AlterModelTable(
            name='sensortype',
            table=None,
        ),
    ]
